# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import retrieval_pb2 as retrieval__pb2


class RetrievalServiceStub(object):
    """The service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Retrieve = channel.unary_unary(
                '/retrieval.RetrievalService/Retrieve',
                request_serializer=retrieval__pb2.RetrievalRequest.SerializeToString,
                response_deserializer=retrieval__pb2.RetrievalReply.FromString,
                )
        self.SetNprobe = channel.unary_unary(
                '/retrieval.RetrievalService/SetNprobe',
                request_serializer=retrieval__pb2.SetNprobeRequest.SerializeToString,
                response_deserializer=retrieval__pb2.SetNprobeReply.FromString,
                )


class RetrievalServiceServicer(object):
    """The service definition.
    """

    def Retrieve(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNprobe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RetrievalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=retrieval__pb2.RetrievalRequest.FromString,
                    response_serializer=retrieval__pb2.RetrievalReply.SerializeToString,
            ),
            'SetNprobe': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNprobe,
                    request_deserializer=retrieval__pb2.SetNprobeRequest.FromString,
                    response_serializer=retrieval__pb2.SetNprobeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'retrieval.RetrievalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RetrievalService(object):
    """The service definition.
    """

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/retrieval.RetrievalService/Retrieve',
            retrieval__pb2.RetrievalRequest.SerializeToString,
            retrieval__pb2.RetrievalReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetNprobe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/retrieval.RetrievalService/SetNprobe',
            retrieval__pb2.SetNprobeRequest.SerializeToString,
            retrieval__pb2.SetNprobeReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
