# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: retrieval.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fretrieval.proto\x12\tretrieval\"\xaf\x01\n\x10RetrievalRequest\x12\r\n\x05query\x18\x01 \x03(\t\x12\x1f\n\x17num_continuation_chunks\x18\x02 \x01(\x05\x12\x16\n\x0enum_neighbours\x18\x03 \x01(\x05\x12\x18\n\x10staleness_offset\x18\x04 \x01(\x05\x12\x0f\n\x07seq_len\x18\x05 \x01(\x05\x12\x10\n\x08interval\x18\x06 \x01(\x05\x12\x16\n\x0euse_perf_model\x18\x07 \x01(\x08\"*\n\x0eRetrievalReply\x12\x18\n\x10retrieved_tokens\x18\x01 \x03(\x05\"\"\n\x10SetNprobeRequest\x12\x0e\n\x06nprobe\x18\x01 \x01(\x05\"\x1f\n\x0eSetNprobeReply\x12\r\n\x05reply\x18\x01 \x01(\t2\x9f\x01\n\x10RetrievalService\x12\x44\n\x08Retrieve\x12\x1b.retrieval.RetrievalRequest\x1a\x19.retrieval.RetrievalReply\"\x00\x12\x45\n\tSetNprobe\x12\x1b.retrieval.SetNprobeRequest\x1a\x19.retrieval.SetNprobeReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retrieval_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RETRIEVALREQUEST']._serialized_start=31
  _globals['_RETRIEVALREQUEST']._serialized_end=206
  _globals['_RETRIEVALREPLY']._serialized_start=208
  _globals['_RETRIEVALREPLY']._serialized_end=250
  _globals['_SETNPROBEREQUEST']._serialized_start=252
  _globals['_SETNPROBEREQUEST']._serialized_end=286
  _globals['_SETNPROBEREPLY']._serialized_start=288
  _globals['_SETNPROBEREPLY']._serialized_end=319
  _globals['_RETRIEVALSERVICE']._serialized_start=322
  _globals['_RETRIEVALSERVICE']._serialized_end=481
# @@protoc_insertion_point(module_scope)
